spring:
  application:
    name: FindClosestRestaurant
  datasource:
   url: jdbc:mysql://localhost:3306/p1
   username: root
   password: Sainithin@2002
  jpa:
   hibernate:
      ddl-auto: update
   show-sql: true